[2024-03-25 14:39:18,551] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: test_dag.test_follow_up_task 2024-03-25T14:28:56.493530+00:00 [queued]>
[2024-03-25 14:39:18,562] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: test_dag.test_follow_up_task 2024-03-25T14:28:56.493530+00:00 [queued]>
[2024-03-25 14:39:18,562] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-03-25 14:39:18,563] {taskinstance.py:1069} INFO - Starting attempt 1 of 6
[2024-03-25 14:39:18,564] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-03-25 14:39:18,579] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): test_follow_up_task> on 2024-03-25T14:28:56.493530+00:00
[2024-03-25 14:39:18,582] {standard_task_runner.py:52} INFO - Started process 57 to run task
[2024-03-25 14:39:18,586] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_dag', 'test_follow_up_task', '2024-03-25T14:28:56.493530+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpv_9a4dhv', '--error-file', '/tmp/tmpebmq_jug']
[2024-03-25 14:39:18,587] {standard_task_runner.py:77} INFO - Job 4: Subtask test_follow_up_task
[2024-03-25 14:39:18,630] {logging_mixin.py:104} INFO - Running <TaskInstance: test_dag.test_follow_up_task 2024-03-25T14:28:56.493530+00:00 [running]> on host b9ac9f1e1168
[2024-03-25 14:39:18,671] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pedro
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=test_follow_up_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-25T14:28:56.493530+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-25T14:28:56.493530+00:00
[2024-03-25 14:39:18,672] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-03-25 14:39:18,673] {bash.py:158} INFO - Running command: echo hello universe!
[2024-03-25 14:39:18,681] {bash.py:169} INFO - Output:
[2024-03-25 14:39:18,682] {bash.py:173} INFO - hello universe!
[2024-03-25 14:39:18,682] {bash.py:177} INFO - Command exited with return code 0
[2024-03-25 14:39:18,713] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=test_follow_up_task, execution_date=20240325T142856, start_date=20240325T143918, end_date=20240325T143918
[2024-03-25 14:39:18,742] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-25 14:39:18,760] {local_task_job.py:146} INFO - Task exited with return code 0
